CREATE TABLE "sdr_agents" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"company_id" uuid NOT NULL,
	"name" text NOT NULL,
	"display_name" text NOT NULL,
	"is_active" boolean DEFAULT false NOT NULL,
	"product_name" text,
	"product_description" text,
	"offer_description" text,
	"prompt" text,
	"first_message_prompt" text,
	"followup_prompt" text,
	"ai_provider" text DEFAULT 'openai' NOT NULL,
	"ai_model" text DEFAULT 'gpt-4o-mini' NOT NULL,
	"ai_temperature" real DEFAULT 0.4 NOT NULL,
	"ai_max_output_tokens" integer DEFAULT 800 NOT NULL,
	"openai_api_key_encrypted" text,
	"openrouter_api_key_encrypted" text,
	"uazapi_base_url" text,
	"uazapi_instance_id" text,
	"uazapi_instance_token_encrypted" text,
	"uazapi_admin_token_encrypted" text,
	"whatsapp_number" text,
	"timezone" text DEFAULT 'America/Sao_Paulo' NOT NULL,
	"send_window_start" text DEFAULT '08:00' NOT NULL,
	"send_window_end" text DEFAULT '18:00' NOT NULL,
	"send_days_of_week" text DEFAULT '1,2,3,4,5' NOT NULL,
	"initial_cooldown_min_minutes" integer DEFAULT 5 NOT NULL,
	"initial_cooldown_max_minutes" integer DEFAULT 15 NOT NULL,
	"followup_enabled" boolean DEFAULT true NOT NULL,
	"followup_after_hours" integer DEFAULT 24 NOT NULL,
	"followup_cooldown_min_minutes" integer DEFAULT 10 NOT NULL,
	"followup_cooldown_max_minutes" integer DEFAULT 30 NOT NULL,
	"daily_initial_send_limit" integer DEFAULT 50 NOT NULL,
	"daily_followup_send_limit" integer DEFAULT 50 NOT NULL,
	"response_delay_base_ms" integer DEFAULT 1200 NOT NULL,
	"response_delay_per_char_ms" integer DEFAULT 35 NOT NULL,
	"response_delay_max_ms" integer DEFAULT 12000 NOT NULL,
	"message_split_max_chars" integer DEFAULT 450 NOT NULL,
	"human_pause_hours" integer DEFAULT 24 NOT NULL,
	"handoff_name" text,
	"handoff_phone" text,
	"handoff_message_template" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "sdr_agents" ADD CONSTRAINT "sdr_agents_company_id_companies_id_fk" FOREIGN KEY ("company_id") REFERENCES "public"."companies"("id") ON DELETE cascade ON UPDATE no action;